//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace BOBDrive.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class FileChunk
    {
        public int Id { get; set; }
        public string FileIdForUpload { get; set; }
        public int ChunkNumber { get; set; }
        public string ChunkFilePath { get; set; }
        public System.DateTime UploadedAt { get; set; }
    }
}
