//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace BOBDrive.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class ShareableLink
    {
        public int Id { get; set; }
        public int FileId { get; set; }
        public string Token { get; set; }
        public string PasswordHash { get; set; }
        public System.DateTime CreatedAt { get; set; }
        public Nullable<System.DateTime> ExpiresAt { get; set; }
    
        public virtual File File { get; set; }
    }
}
